### ISSUE TITLE
*.* default as filter excludes files in target folder 

### ISSUE THREAD

**Issue by matthiasg** [jantimon/html-resource-hints-plugin#1]
Great addition to a webpack build pipeline! Works great. I especially like the way the HTMLPlugin is used to carry per file prefetch/preload options.

Two remarks:

Using `*.*` as default excludes files inside of e.g /dist folders. minimatch uses globbing so maybe it should default to `'**/*.js'` or similar. Or at least that might be mentioned in the README.

The name of the project might be better served having webpack in it. It seems to be a convention for many webpack plugins :)

**Comment by jantimon** [comment]
You are right with both points.

I changed the default to `**/*.*` and released it under the name resource-hints-webpack-plugin
