### ISSUE TITLE
JS files must have `as='script` attr

### ISSUE THREAD

**Issue by matthiasg** [jantimon/html-resource-hints-plugin#2]
`<link rel="preload">` must have an `as="script"` attribute for scripts

**Comment by matthiasg** [comment]
can be added by extending `createResourceHintTag` function to detect type of url using the node url parser 

EDIT: of course only for preload tags

**Comment by jantimon** [comment]
Thanks a lot - I added the following list of file extensions:

https://github.com/jantimon/resource-hints-webpack-plugin/blob/master/index.js#L7-L17

From: https://w3c.github.io/preload/#link-element-interface-extensions

Do you think that's enough?

**Comment by matthiasg** [comment]
looks great .. could have sworn i had written this 22 days ago. Mail never processed it seems. Sorry for that.
